### ISSUE TITLE
Unicode word boundaries cause URLs to be overlooked in Full Text Searches

### ISSUE THREAD

**Issue by lamemakes** [signalapp/Signal-FTS5-Extension#1]
Hey all!

After doing some poking it appears that due to UAX word boundaries [not breaking words across certain punctuation](http://www.unicode.org/reports/tr29/#WB6), URLs that include "www" (or any subdomain, for that matter) won't be picked up in [Full Text Searches](https://github.com/signalapp/Signal-Desktop/issues/6460).

**Comment by lamemakes** [comment]
I took a brief stab at this but am looking for feedback before a PR or moving further: [here](https://github.com/signalapp/Signal-FTS5-Extension/compare/main...lamemakes:Signal-FTS5-Extension:url-fixes)

What was done here was a Regex find & replace subdomain periods with spaces to allow for tokenizing. The expression used here could definitely be tweaked more to work in a wider variety of cases, but covers most base cases: https://regex101.com/r/xqSWzB/1. In it's current form, it will transform the following:
`http://aws.amazon.com` -> `http://aws amazon.com`
`http://www.signal.org` -> `http://www signal.org`
`www.wunderground.com` -> `www wunderground.com`


While this specifically applies to URLs, a case could potentially be made for any periods sandwiched between alphabetic characters (ex. ```hey.dude```)

**Comment by lamemakes** [comment]
Also will note that URLs that do not have a troublesome subdomain (ie. `https://github.com`) not be touched by this fix

**Comment by indutny-signal** [comment]
Sorry, but this is by design to support words and abbreviations like `e.g.`. See the spec: https://unicode.org/reports/tr29/#WB6

> Do not break letters across certain punctuation, such as within “e.g.” or “example.com”.
